MyWatchStore/MyWatchStore/MyWatchStore/Controllers/WatchStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyWatchStore.Models;
using PagedList;
using PagedList.Mvc;

namespace MyWatchStore.Controllers
{
    public class WatchStoreController : Controller
    {
        WatchStoreDataContext data = new WatchStoreDataContext();

        // GET: WatchStore
        public ActionResult Index(int? page)
        {
            if (page == null) {
                page = 1;
            }

            int pageSize = 16;
            int pageNumber = (page ?? 1);

            var dongHo = (from dh in data.DONGHOs select dh).OrderBy(x => x.MaDH);
            return View(dongHo.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Category() {
            var hangDH = from hangdh in data.HANGs select hangdh;
            return PartialView(hangDH);
        }

        public ActionResult ViewCategory(string maHang, int ? page) {
            if (page == null)
            {
                page = 1;
            }

            int pageSize = 16;
            int pageNumber = (page ?? 1);

            var dongHoHang = (from dhh in data.DONGHOs where dhh.MaHang == maHang select dhh).OrderBy(m => m.MaDH);
            return View(dongHoHang.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Detail(int maDH) {
            var dh = from dongHo in data.DONGHOs where dongHo.MaDH == maDH select dongHo;
            return View(dh.Single());
        }

        public ActionResult DetailInfo(string maHang)
        {
            var detail = from dt 
                         in data.HANGs
                         where dt.MaHang == maHang
                         select dt;
            return PartialView(detail.Single());
        }
    }
}

MyWatchStore/MyWatchStore/MyWatchStore/Views/WatchStore/Category.cshtml
@foreach (var dh in Model) {
    <li><a href="@Url.Action("ViewCategory", "WatchStore", new { maHang = dh.MaHang})">@dh.TenHang</a></li>
}

MyWatchStore/MyWatchStore/MyWatchStore/Views/WatchStore/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_WatchStoreLayout.cshtml";
}
<h2>@Model.TenDH</h2>
<hr />
<img src="~/DataImages/@Model.Image" alt="@Model.TenDH" />
<h3>THÔNG TIN</h3>
<hr />
@Html.Action("DetailInfo", "WatchStore", new { maHang = Model.MaHang })
<h3>THÔNG TIN CHI TIẾT</h3>
<hr />
<p>Xuất xứ: </p>
<p>Giới tính: </p>
<p>Kính: </p>
<p>Máy: </p>
<p>Đường kính mặt số: </p>
<p>Bề dày mặt số: </p>
<p>Màu mặt số: </p>
<p>Dây đeo: </p>
<p>Chống nước: </p>
<p>Chức năng: </p>
<a href="@Url.Action("AddToCart", "Cart", new { @maDH = @Model.MaDH, @strUrl = Request.Url.ToString()})">Thêm vào giỏ hàng</a>

MyWatchStore/MyWatchStore/MyWatchStore/Views/WatchStore/DetailInfo.cshtml
<p>@Model.Detail</p>

MyWatchStore/MyWatchStore/MyWatchStore/Views/WatchStore/Index.cshtml
@using MyWatchStore.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<DONGHO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_WatchStoreLayout.cshtml";
}

@foreach (var dh in Model)
{
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3">
        <div style="height: 470px" class="thumbnail">
            <img src="~/DataImages/@dh.Image" alt="">
            <div class="caption">
                <h3 style="color: black; text-decoration: none;">@dh.TenDH</h3>
                <p style="color: black; text-decoration: none;">
                    @dh.Gia đ
                </p>
                <p>
                    <a href="@Url.Action("AddToCart", "Cart", new { maDH = dh.MaDH, strUrl = Request.Url.ToString()})" class="btn btn-primary"><i class="fa fa-shopping-cart"></i></a>
                    <a href="@Url.Action("Detail", "WatchStore", new { maDH = dh.MaDH})" class="btn btn-default">CHI TIẾT</a>
                </p>
            </div>
        </div>
    </div>
}
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="menu-trang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

MyWatchStore/MyWatchStore/MyWatchStore/Views/WatchStore/ViewCategory.cshtml
@using MyWatchStore.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<DONGHO>

@{
    ViewBag.Title = "ViewCategory";
    Layout = "~/Views/Shared/_WatchStoreLayout.cshtml";
}
@foreach (var dh in Model)
{
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3">
        <div style="height: 470px" class="thumbnail">
            <img src="~/DataImages/@dh.Image" alt="">
            <div class="caption">
                <h3 style="color: black; text-decoration: none;">@dh.TenDH<
                    
                <p style="color: black; text-decoration: none;">
                    @dh.Gia đ
                </p>
                <p>
                    <a href="@Url.Action("AddToCart", "Cart", new { maDH = dh.MaDH, strUrl = Request.Url.ToString()})" class="btn btn-primary">MUA</a>
                    <a href="@Url.Action("Detail", "WatchStore", new { maDH = dh.MaDH})" class="btn btn-default">CHI TIẾT</a>
                </p>
            </div>
        </div>
    </div>
}
<br />
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="menu-trang">
    @Html.PagedListPager(Model, page => Url.Action("ViewCategory", new { page = page }))
</div>